export const chartsTypes = [
    "Line Chart",
    "Bar Chart (Vertical and Horizontal)",
    "Column Chart",
    "Area Chart",
    "Pie Chart",
    "Doughnut Chart",
    "Scatter Plot",
    "Bubble Chart",
    "Histogram",
    "Box Plot",
    "Radar Chart",
    "Polar Area Chart",
    "Gauge Chart",
    "Heatmap",
    "Treemap",
    "Sankey Diagram",
    "Funnel Chart",
    "Waterfall Chart",
    "Candlestick Chart",
    "Gantt Chart",
]