export enum GraphType {
    TwoLevelPieChart = 'Two Level PieChart',
    TwoSimplePieChart = 'Two Simple PieChart',
    StackedAreaChart = 'Stacked Area Chart',
    PieChartWithPaddingAngle = 'Pie ChartWith Padding Angle',
    MultipleYAxesScatterChart = 'Multiple YAxesScatter Chart',
    LineChartWithReferenceLines = 'Line Char tWith Reference Lines',
    LineChartConnectNulls = 'Line Chart Connect Nulls',
    BasicSparkLine = 'Basic Spark Line',
    BasicScatterChart = 'Basic Scatter Chart',
    StraightAnglePieChart = 'Straight Angle PieChart',
    BasicLineChart = 'Basic Line Chart',
    BasicBars = 'Basic Bars',
    AreaLineChart = 'AreaLine Chart',
  }