export const FETCH_NUMERIC_REQUEST = 'FETCH_NUMERIC_REQUEST';
export const FETCH_NUMERIC_SUCCESS = 'FETCH_NUMERIC_SUCCESS';
export const FETCH_NUMERIC_FAILURE = 'FETCH_NUMERIC_FAILURE';
export const FETCH_NUMERIC_CLEAR = 'FETCH_NUMERIC_CLEAR';

export const FETCH_RANDOM_REQUEST = 'FETCH_RANDOM_REQUEST';
export const FETCH_RANDOM_SUCCESS = 'FETCH_RANDOM_SUCCESS';
export const FETCH_RANDOM_FAILURE = 'FETCH_RANDOM_FAILURE';